logo_url: /assets/logos/extractors/prometheus.png
variant: signal-ai
usage: ''
settings_preamble: ''
settings_group_validation: []
settings: []
repo: https://github.com/signal-ai/tap-prometheus
pip_url: git+https://github.com/signal-ai/tap-prometheus.git
next_steps: ''
namespace: tap_prometheus
name: tap-prometheus
maintenance_status: active
label: Prometheus
keywords: []
domain_url: ''
capabilities:
- catalog
- discover
- state
