name: Check YAML schemas

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: Check ${{ matrix.plugin_type }} schemas
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin_type:
        - extractors
        - files
        - loaders
        - mappers
        - orchestrators
        - transformers
        - transforms
        - utilities
    steps:
    - uses: actions/checkout@v3

    - name: Get changed files in the docs folder
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files: |
          _data/meltano/${{ matrix.plugin_type }}/**/*.yml

    - name: Install check-jsonschema
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        pipx install check-jsonschema
        pipx inject check-jsonschema rfc3986-validator

    - name: Check YAML schemas
      if: steps.changed-files.outputs.any_changed == 'true'
      run: >
        check-jsonschema
        --schemafile schemas/plugin_definitions/${{ matrix.plugin_type }}.schema.json
        ${{ steps.changed-files.outputs.all_changed_files }}
